policies:
  - name: ec2-public-ingress-hubfinding
    description: filters for ec2 instances with security-groups with ingress rule allowing public access
    resource: ec2
    mode:
        type: hub-finding
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        memory: 128
        packages: [botocore, boto3, urllib3]
    filters:
      - type: event
        key: detail.findings[0].Resources[0].Type
        value: AwsEc2Instance 
      - type: value
        key: PublicIpAddress
        value: not-null
      - type: value
        key: IamInstanceProfile
        value: not-null
      # describe level data does not appear to be available
      - type: security-group
        key: IpPermissions[].IpRanges[].CidrIp
        value_type: swap
        op: in
        value: "0.0.0.0/0" # anywhere
      - type: check-permissions
        match: allowed
        match-operator: or
        actions:
          - s3:GetObject
          - s3:*
      # is member of ASG due to the asg action, should have a non-asg version of the policy as well
      #- "tag:aws:autoscaling:groupName": not-null
    actions:
      # Enable termination protection - https://github.com/cloud-custodian/cloud-custodian/issues/2545
      # snapshot the disk for forensics
      - type: snapshot
        copy-tags: [Name]
      # Add forensic SG for responser ingress to trusted network source
      # - modify-security-groups action to be added in future version of this workshop
      # Grab memory if have ssh or SSM
      # - invoke-sfn action to be added in future version of this workshop
      # Remove priviledges from the instance
      - type: set-instance-profile
      # remove from any ASG or clustering - Enhancement request (at least for ASG.  Clustering TBD)
      #- type: send-command
      #  command:
      #    DocumentName: AWS-ASGEnterStandby # Looking for an SSM doc which does Detach from ASG instead, or implementation of https://github.com/cloud-custodian/cloud-custodian/issues/4603
      # Remove all SG's but forensic SG, another modify-security-group action
